# Generated by Django 4.2 on 2023-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_rewarded_referral_count',
            field=models.IntegerField(default=0),
        ),
    ]
