# Generated by Django 4.2 on 2023-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_rewarded_referral_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
