# Generated by Django 4.2 on 2023-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telegram_task_user_twitter_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whitelist_task',
            field=models.IntegerField(default=0),
        ),
    ]
